/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by AddOnGenerator 1.0.0 from webgme on Tue Dec 08 2015 15:17:06 GMT-0600 (CST).
 */

define([
    'addon/AddOnBase',
    './superheroes.json'
], function (
    AddOnBase,
    SuperHeroNames
) {
    'use strict';

    var NAME_COUNT = SuperHeroNames.length;
    /**
     * Initializes a new instance of NameMaker.
     * @class
     * @augments {AddOnBase}
     * @classdesc This class represents the addOn NameMaker.
     * @constructor
     */
    var NameMaker = function (mainLogger, gmeConfig) {
        // Call base class' constructor.
        AddOnBase.call(this, mainLogger, gmeConfig);
    };

    // Prototypal inheritance from AddOnBase.
    NameMaker.prototype = Object.create(AddOnBase.prototype);
    NameMaker.prototype.constructor = NameMaker;

    /**
     * Gets the name of the NameMaker.
     * @returns {string} The name of the AddOn.
     * @public
     */
    NameMaker.prototype.getName = function () {
        return 'NameMaker';
    };

    /**
     * Gets the semantic version (semver.org) of the NameMaker.
     * @returns {string} The version of the AddOn.
     * @public
     */
    NameMaker.prototype.getVersion = function () {
        return '0.1.0';
    };

    /**
     * This is invoked each time changes in the branch of the project are done. AddOns are allowed to make changes on
     * an update, but should not persist by themselves. (The AddOnManager will persist after each addOn has had its way
     * ordered by the usedAddOn registry in the rootNode).
     * Before each invocation a new updateResult is created which should be returned in the callback. There is no need
     * for the AddOn to report if it made changes or not, the monitor/manager will always persist and if there are no
     * changed objects - it won't commit to the storage.
     * @param {object} rootNode
     * @param {object} commitObj
     * @param {function(Error, AddOnUpdateResult)} callback
     */
    NameMaker.prototype.update = function (rootNode, commitObj, callback) {
        var newName = NameMaker.getName();
        console.log(`name is ${newName}`);
        this.logger.info('NameMaker in update at commitHash', commitObj._id);

        if (this.core.getAttribute(rootNode, 'name') !== newName) {
            this.logger.info('NameMaker changing name of root to committer(s): ', newName);
            this.core.setAttribute(rootNode, 'name', newName);
            this.addCommitMessage('Changed rootNode name to "' + newName + '"');
        }

        callback(null, this.updateResult);
    };

    /**
     * Called once when the addOn is started for the first time.
     * @param {object} rootNode
     * @param {object} commitObj
     * @param {function(Error, AddOnUpdateResult} callback
     */
    NameMaker.prototype.initialize = function (rootNode, commitObj, callback) {
        this.logger.info('NameMaker got initialized at commitHash', commitObj._id);

        this.update(rootNode, commitObj, callback);
    };

    NameMaker.getName = function() {
        return SuperHeroNames[Math.floor(Math.random()*NAME_COUNT)];
    };

    return NameMaker;
});
